### ISSUE TITLE
Editable Reblogs post error

### ISSUE THREAD

**Issue by kuraidalkai** [new-xkit/XKit#1875]
*Please describe what actions we can take to reproduce the bug you found, including any links or screenshots that might help us figure out what's going on.*

Placed under a Read More and won't let me post.

-----------

```
Error: Syntax error, unrecognized expression: [[MORE]]<div class="xkit-button default xreadmore block" xreadmore-url="lordofoblivion" xreadmore-id="622581637101813760">
					Read More Now!
				</div><div class="media-holder media-holder-draggable media-holder-hr" contenteditable="false" draggable="true">[[MORE]]</div><p>{☁}&nbsp; She felt maybe she was forgetting something important, but couldn't quite think of what it possibly was. So she pushed it aside for now. Though there was certainly a mix between re-awakened teenage hormones and the venom still polluting her bloodstream… After it was all over, perhaps they both could get some sleep and have a talk…. But for the time being--<b><br></b></p><p>Elrena hitched her upper thigh up between his legs gently, humming contently as she lifted from him slightly, bruising well started- moving onto the other side of his neck.&nbsp;</p><p>Her left hand slipped down, unbuttoning his shirt a couple of times as she bit and sucked a bit more deeply at the other side of his neck, nails trailing the bruised skin and collar bone as she lifted her head from the other side with a smile.&nbsp;</p><p>"You are such a pretty boy… You know that?" She laughed quietly to herself as she shook her head, raking her nails gently across the exposed skin; pausing over his heart.</p><p>There it was, a heartbeat. So longingly missed.. She wasn't letting it go now.</p>
    at Function.se.error (chrome-extension://inobiceghmpkaklcknpniboilbjmlald/jquery.js:2:13061)
    at se.tokenize (chrome-extension://inobiceghmpkaklcknpniboilbjmlald/jquery.js:2:21072)
    at se.select (chrome-extension://inobiceghmpkaklcknpniboilbjmlald/jquery.js:2:21901)
    at Function.se [as find] (chrome-extension://inobiceghmpkaklcknpniboilbjmlald/jquery.js:2:6893)
    at k.fn.init.find (chrome-extension://inobiceghmpkaklcknpniboilbjmlald/jquery.js:2:24471)
    at new k.fn.init (chrome-extension://inobiceghmpkaklcknpniboilbjmlald/jquery.js:2:24960)
    at k (chrome-extension://inobiceghmpkaklcknpniboilbjmlald/jquery.js:2:950)
    at Object.wrap_html_links (xkit/editable_reblogs.js:206:15)
    at Object.build_common_svc_request (xkit/editable_reblogs.js:462:31)
    at Object.build_svc_request (xkit/editable_reblogs.js:388:22)
```

System Data |   
----------- | -----------
state | success
ER Version | 3.3.13
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
XKit Version | 7.9.2
Patches Version | 7.4.3
Extensions | xkit_main, xkit_patches, xkit_preferences, xkit_updates, xinbox, one_click_postage, one_click_reply, tweaks, go_to_dash, autoscroll, blacklist, editable_reblogs, elevator, find_inactives, norecommended, satsukimous, shorten_posts, soft_refresh, themes, activity_plus, anti_capitalism, drafts_plus, auto_tagger, mass_deleter, quick_tags, retags, tag_replacer, mutualchecker, shuffle_queue, mass_plus, outbox, view_my_tags, read_more_now
URL | https://www.tumblr.com/neue_web/iframe/reblog/622581637101813760/QT5y9m4I

**Comment by kuraidalkai** [comment]
![image](https://user-images.githubusercontent.com/63219751/86488735-9b979c00-bd27-11ea-9d92-81d312ed0705.png)
